### ISSUE TITLE
US 1 - Input fields for maincolors

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/capstone-nils#1]
## Value proposition

As a user
I want to see 3 input fields for the main colors so that I can indicate the main colors of the room.

## Description

![Image](https://user-images.githubusercontent.com/125801955/250975114-10e996f6-41ef-4170-92c8-f8897dfc05a3.png)

## Acceptance criteria

- [ ] three input fields are visible
- [ ] when clicking the inputs you can choose a color by the color picker
- [ ] the labels of the inputs should display the text "color 1 - 3"

## Tasks

- [ ] create the input component (type color)

**Comment by vaupunkt** [comment]
maybe you could add how you want to be able to choose the colors?  
so it would be more detailed what you want to code :)

**Comment by MonaHer** [comment]
LGTM :) I guess there's only one little typo: At the end of line 2 of the Acceptance criteria the word "label" (?) is missing
