### ISSUE TITLE
US 2 - Button for creating color suggestion

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/capstone-nils#3]
## Value proposition

As a user
I want to see a button to generate two random colors so I have the dummy for my upcoming color suggestions for the wall based on the selected main colors.

## Description

![Image](https://github.com/NilsOt1/capstone-nils/assets/125801955/cf226f14-1833-4871-a81f-fec5bc4fb775)

## Acceptance criteria

- [ ] a `button` with the text "Color me!" is visible
- [ ] when clicking the `button`, I get to a new Page
- [ ] there are two `div` on the new Page which display two random colors

## Tasks

- [ ] create a branch
- [ ] create a `button` component which displays the text "Color me!"
- [ ] implement the logic to store the selected main colors
- [ ] build the logic to generate two random colors
- [ ] create a `div` component which get colored by the function
