### ISSUE TITLE
US 3 - Show the current room

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/capstone-nils#6]
## Value proposition

As a user
I want to see the current room so I know which room I am editing at the moment.

## Description

![Image](https://user-images.githubusercontent.com/125801955/252700617-8964e654-6458-4906-8c1f-a700e9fc9def.png)

## Acceptance criteria

- [] a field displaying the current room is visible
- [] the text of the field should be "Living room"

## Tasks

- [] create a branch
- [] create a select-component
- [ ] implement the component on the main page and the suggestions page
