### ISSUE TITLE
US 5 - page for rooms

### ISSUE THREAD

**Issue by NilsOt1** [NilsOt1/capstone-nils#9]
## Value proposition

As a user
I want to see a overview page with a predefined room named "living room" so I have an overview over the existing rooms

## Description

![Image](https://user-images.githubusercontent.com/125801955/253324452-37cf4e38-0ca9-4001-81b1-13637e0b22b8.png)

## Acceptance criteria

- [x] the overview page with one existing room is visible

## Tasks

- [x] create a `branch`
- [x] create a `card` component for the rooms
- [x] implement the component on the overview page

**Comment by vaupunkt** [comment]
short and easy to understand :) 
LGTM ⛵️
